[package]
name = "astrodasha_microservice"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
